.github/workflows/release.yml, .github/workflows/test.yml, README.md, karma.conf.js
Signed-off-by: Florin Hillebrand <florin.hillebrand@tuwien.ac.at>
=> [CI] Add workflows for PullRequests and container release.

src/app/dmp/data-deletion/data-deletion.component.html, src/app/dmp/data-deletion/data-deletion.component.spec.ts, src/app/dmp/data-deletion/data-deletion.component.ts, src/app/dmp/data-deletion/data-deletion.module.ts, src/app/dmp/people/confirm-deletion-dialog.html, src/app/dmp/people/people.component.spec.ts, src/app/dmp/people/people.component.ts, src/app/dmp/people/people.module.ts, src/app/domain/dataset.ts, src/app/mocks/dataset-mocks.ts, src/app/services/form.service.ts, src/app/version/version-view-sections/version-view-datasets/version-view-datasets.component.html, src/assets/i18n/templates/en.json
=> Add person responsible for dataset deletion

src/app/services/backend.service.ts, src/assets/i18n/en.json
=> Document export error notification

src/app/app.component.ts, src/app/dmp/dmp.component.ts, src/app/services/logger.service.spec.ts, src/app/services/logger.service.ts
=> Add LoggerService

src/app/dmp/repo/retention-period/retention-period.component.html, src/app/dmp/repo/retention-period/retention-period.component.ts
=> [Bugfix] Display retention period for new datasets only

package-lock.json, package.json, src/app/app.component.spec.ts, src/app/app.module.ts, src/app/plans/plans.component.html, src/app/plans/plans.module.ts, src/app/widgets/dmp-table/dmp-table.component.html, src/app/widgets/dmp-table/dmp-table.component.spec.ts, src/app/widgets/dmp-table/dmp-table.component.ts, src/app/widgets/dmp-table/dmp-table.module.ts
closes #9
-  sort behavior added to the table and the header row of each column header cell is sorted.
=> sort my DMPs list

libs/damap/src/lib/shared/input-wrapper/input-wrapper.component.ts, libs/damap/src/lib/shared/textarea-wrapper/textarea-wrapper.component.ts
=> [Bugfix] Fix input fields maxlength

libs/damap/src/assets/i18n/templates/en.json, libs/damap/src/lib/components/dmp/doc-data-quality/doc-data-quality.component.html, libs/damap/src/lib/components/dmp/doc-data-quality/doc-data-quality.component.ts, libs/damap/src/lib/components/dmp/specify-data/specify-data.component.html, libs/damap/src/lib/components/version/version-view-sections/version-view-doc-data-quality/version-view-doc-data-quality.component.html, libs/damap/src/lib/domain/dmp.ts, libs/damap/src/lib/mocks/dmp-mocks.ts, libs/damap/src/lib/services/form.service.ts, libs/damap/src/lib/services/summary.service.spec.ts, libs/damap/src/lib/services/summary.service.ts, libs/damap/src/lib/store/states/form.state.ts
=> Add documentation question to step 4

.gitignore, libs/damap/src/assets/i18n/templates/en.json
=> change PL text to indicate new behavior,

libs/damap/src/assets/i18n/templates/en.json, libs/damap/src/lib/components/version/version-list/version-list.component.spec.ts, libs/damap/src/lib/components/version/version-list/version-list.component.ts, libs/damap/src/lib/components/version/version-table/version-table.component.html, libs/damap/src/lib/components/version/version-table/version-table.component.ts
=> Fix admin version overview

libs/damap/src/lib/components/version/version-view-sections/version-view-costs/version-view-costs.component.html
=> [Bugfix] Fix cost type in version view

libs/damap/src/lib/components/dmp/project/project-list/project-list.component.html
As far as I understood the task before our meeting, I could solve it according to my understanding (see attachment).
If something else is meant, we can discuss it on Thursday. So I will continue with the other topic.
=> disappeared the selected project

libs/damap/src/assets/i18n/plans/en.json, libs/damap/src/lib/widgets/dmp-table/dmp-table.component.css, libs/damap/src/lib/widgets/dmp-table/dmp-table.component.html, libs/damap/src/lib/widgets/dmp-table/dmp-table.component.ts, libs/damap/src/lib/widgets/dmp-table/dmp-table.module.ts
=> 36 enhance plans overview

libs/damap/src/assets/i18n/en.json
=> change popup text

libs/damap/src/lib/components/dmp/dmp.component.css
=> [Bugfix] Make sure dmp-actions bar sticks to bottom

libs/damap/src/assets/i18n/access/en.json, libs/damap/src/lib/components/access/access.component.html, libs/damap/src/lib/widgets/dmp-table/dmp-table.component.html
Adds additional info about contributors to access view.
refs https://github.com/tuwien-csd/damap-backend/issues/52
=> Add access info

.prettierrc
Config
Update prettier ruleset for consistent formatting.
=> Update prettier rules

apps/damap-frontend-e2e/cypress.config.ts, apps/damap-frontend-e2e/src/e2e/delete-dmp.cy.ts
Test
Adds an e2e test for DMP deletion
closes GH-72
=> Add delete dmp e2e test

libs/damap/src/lib/components/dmp/doc-data-quality/doc-data-quality.component.css, libs/damap/src/lib/components/dmp/legal-ethical-aspects/legal-ethical-aspects.component.css
=> position multipule choice - show the question itsef

libs/damap/src/assets/i18n/templates/en.json
Changes to text boxes
closes GH-
=> change text

libs/damap/src/lib/components/dmp/costs/costs.component.html, libs/damap/src/lib/components/dmp/costs/costs.component.ts
Changed sequence of dropdown items for costtype list
closes GH-
=> change sequence of the list

libs/damap/src/lib/components/dmp/specify-data/dataset-dialog/dataset-dialog.component.html, libs/damap/src/lib/components/dmp/specify-data/dataset-dialog/dataset-dialog.component.ts, libs/damap/src/lib/domain/enum/identifier-type.enum.ts, libs/damap/src/lib/domain/identifier-type.ts
Change sorting for identifier list for reused datasets - contains only 5 from the list
closes GH-
=> change sorting for identifier list for reused dataset

libs/damap/src/lib/components/dmp/people/contributor-filter.pipe.spec.ts, libs/damap/src/lib/components/dmp/people/contributor-filter.pipe.ts, libs/damap/src/lib/domain/contributor.ts, libs/damap/src/lib/services/form.service.spec.ts, libs/damap/src/lib/services/form.service.ts
Bugfix
Extract contributor comparison and move to own function. Reuse this function where applicable.
Fixes issue with selecting ORCID contributor as contact.
closes GH-98
=> create reusable method for comparing contributors

apps/damap-frontend-e2e/src/e2e/gdpr.cy.ts, apps/damap-frontend/src/app/app.module.ts, apps/damap-frontend/src/app/components/layout/layout.component.css, apps/damap-frontend/src/app/components/layout/layout.component.html, apps/damap-frontend/src/assets/i18n/layout/en.json, libs/damap/src/assets/i18n/gdpr/de.json, libs/damap/src/assets/i18n/gdpr/en.json, libs/damap/src/lib/components/gdpr/gdpr.component.css, libs/damap/src/lib/components/gdpr/gdpr.component.html, libs/damap/src/lib/components/gdpr/gdpr.component.spec.ts, libs/damap/src/lib/components/gdpr/gdpr.component.ts, libs/damap/src/lib/damap.module.ts, libs/damap/src/lib/domain/gdpr.ts, libs/damap/src/lib/services/backend.service.spec.ts, libs/damap/src/lib/services/backend.service.ts
Feature
Adds a view for GDPR data. Link in footer.
https://github.com/tuwien-csd/damap-backend/pull/80
closes https://github.com/tuwien-csd/damap-backend/issues/77
=> Add GDPR view

apps/damap-frontend/src/app/components/layout/layout.component.css, apps/damap-frontend/src/app/components/layout/layout.component.html, apps/damap-frontend/src/assets/i18n/layout/de.json, apps/damap-frontend/src/assets/i18n/layout/en.json
Feature: Update footer with legal links and localization support
This PR updates the website footer by adding new legal links (Data Protection Declaration, Impressum, and Terms and Conditions) and providing localization support for both English and German languages.
No breaking changes are introduced by this PR.
Please focus on the implementation of the new footer links and the localization updates. Check for  CSS styles, and localization keys in both the HTML and the JSON localization files.
No additional dependencies are required for this PR.
closes GH-
=> update footer with required legal links

libs/damap/src/lib/components/dmp/licenses/licenses.component.html
=> Invert sequence of licensing

libs/damap/src/assets/i18n/info/en.json, libs/damap/src/lib/components/dmp/project/project.component.html, libs/damap/src/lib/components/dmp/project/project.module.ts
Add info text to project step regarding export if no funder information is available.
depends on https://github.com/tuwien-csd/damap-frontend/issues/58
closes GH-59
=> Add info for missing funder information

libs/damap/src/assets/i18n/templates/en.json, libs/damap/src/lib/domain/enum/export-template-type.enum.ts
Feature
Add Horizon Europe export option.
https://github.com/tuwien-csd/damap-backend/pull/118
closes https://github.com/tuwien-csd/damap-backend/issues/47
=> export: add horizon europe option

Dockerfile
Bug would cause different modules, like translate to stop working.
Bugfix
Removed the chmod in Dockerfile
closes GH-
=> Fixed bug caused by chmod in Dockerfile.

libs/damap/src/assets/i18n/dashboard/en.json
This PR replaces the existing link in the 'What is a DMP?' section with a more relevant one that leads directly to detailed information about the FAIR Principles and link to explain DMP.
+ https://github.com/tuwien-csd/damap-frontend/issues/147 -  included
closes GH-
=> :busts_in_silhouette: update links for DMP info

libs/damap/src/lib/components/dmp/licenses/licenses.module.ts, libs/damap/src/lib/components/dmp/project/manual-project-input/manual-project-input.component.html, libs/damap/src/lib/components/dmp/project/project.component.html, libs/damap/src/lib/components/dmp/project/project.module.ts
Calandar date formats: DD/MM/YYYY
closes GH-
=> Ensure consistency for calandar date formats

libs/damap/src/assets/i18n/info/en.json, libs/damap/src/assets/i18n/templates/en.json, libs/damap/src/lib/components/dmp/legal-ethical-aspects/ethical-aspects/ethical-aspects.component.html
Feature
Adds real example links to the Ethical section. uses TU Wien as an example institution. The frontpage links were kept institution-neutral.
closes GH-163
=> Ethical: Update example links

Dockerfile
Reverts tuwien-csd/damap-frontend#183
=> Revert "Container build publish issue"

Dockerfile, package.json
=> Revert 183 182 global upgrade angular from 14 to 17 175 151

Dockerfile, package.json
=> Fix permission denied error during docker build with npm installation
